// Node JS In-build module
import fs from "fs/promises";
import path from "path";
import Head from "next/head";
import React, { useState } from "react";
import ProfileCard from "../components/ProfileCard";

import Card from "../components/Card";

export default function Home({ dataArr }) {
  const [timeframe, setTimeframe] = useState("daily");
  return (
    <div className="laptop:flex ">
      <Head>
        <title>Time tracking | FEM </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ProfileCard timeframe={timeframe} setTimeframe={setTimeframe} />
      <div className="grid flex-1 gap-5 mt-8 grid-cols-autofill laptop:mt-0 laptop:ml-8 laptop:grid-rows-2">
        {dataArr.map((data) => (
          <Card data={data} key={data.title} timeframe={timeframe} />
        ))}
      </div>
    </div>
  );
}

export async function getStaticProps() {
  //When this file is executed the path of this file be in root project folder.
  const filePath = path.join(process.cwd(), "data", "data.json");
  const jsonData = await fs.readFile(filePath);
  const data = JSON.parse(jsonData);
  return {
    props: {
      dataArr: data,
    },
  };
}
